### PR TITLE
Remove cargo::rustc-check-cfg from build.rs

### LINKED ISSUE #67: Rust 1.76: unsupported output in build script of `crc32c v0.6.6`: `cargo::rerun-if-changed=build.rs`
This line
https://github.com/zowens/crc32c/blob/938eada661e7192491efbd3cc3e40104cfa9ab77/build.rs#L186
unfortunately breaks Rust 1.76 (and probably earlier versions):

```
error: unsupported output in build script of `crc32c v0.6.6`: `cargo::rerun-if-changed=build.rs`
Found a `cargo::key=value` build directive which is reserved for future use.
Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
warning: build failed, waiting for other jobs to finish...

```

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes #67

### CODE REVIEW

**Comment by jayvdb** [comment]
Adding the following to your Cargo.toml will workaround this problem
```toml
[patch.crates-io]
# Workaround for https://github.com/zowens/crc32c/issues/67
crc32c = { git = "https://github.com/jayvdb/crc32c", branch = "crc-i67" }
```

File: build.rs [hunk 1]
```diff
@@ -187,13 +187,11 @@ fn main() {
...
 
     let current_version = {
-        // rmeove prerelease tag for now, if it exists
+        // remove prerelease tag for now, if it exists.
         let vers = version().unwrap();
         Version::new(vers.major, vers.minor, vers.patch)
     };
 
-    // only stable in nightly versions for 1.80 and above
-    println!("cargo::rustc-check-cfg=cfg(armsimd)");
```
Comment (zowens) [inline build.rs:196]: This is necessary for 1.80... can we move this to the `if` block below instead?

**Review by zowens — APPROVED** [review]
